// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package repo

import (
	"context"
)

const countMessagesInThread = `-- name: CountMessagesInThread :one
SELECT COUNT(*) AS count
FROM message
WHERE thread = $1
`

func (q *Queries) CountMessagesInThread(ctx context.Context, thread string) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesInThread, thread)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (thread, sender, content)
VALUES ($1, $2, $3)
RETURNING id, thread, sender, content, created_at
`

type CreateMessageParams struct {
	Thread  string `json:"thread"`
	Sender  string `json:"sender"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Thread, arg.Sender, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Thread,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessageByID = `-- name: DeleteMessageByID :exec
DELETE FROM message
WHERE id = $1
`

func (q *Queries) DeleteMessageByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMessageByID, id)
	return err
}

const getAllMessages = `-- name: GetAllMessages :many
SELECT id, thread, sender, content, created_at FROM message
ORDER BY created_at DESC
`

func (q *Queries) GetAllMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.Query(ctx, getAllMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Thread,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, thread, sender, content, created_at FROM message
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Thread,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesByThread = `-- name: GetMessagesByThread :many
SELECT id, thread, sender, content, created_at FROM message
WHERE thread = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMessagesByThread(ctx context.Context, thread string) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByThread, thread)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Thread,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
UPDATE message
SET content = $2
WHERE id = $1
`

type UpdateMessageContentParams struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.Exec(ctx, updateMessageContent, arg.ID, arg.Content)
	return err
}
