// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CountMessagesInThread(ctx context.Context, thread string) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteMessageByID(ctx context.Context, id string) error
	GetAllMessages(ctx context.Context) ([]Message, error)
	GetMessageByID(ctx context.Context, id string) (Message, error)
	GetMessagesByThread(ctx context.Context, thread string) ([]Message, error)
	UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error
}

var _ Querier = (*Queries)(nil)
